### ISSUE TITLE
Mininval remote submissions failing

### ISSUE THREAD

**Issue by FedeClaudi** [snel-repo/falcon-challenge#21]
Hello, 

Thank you so much for organizing FALCON - I think the field will benefit hugely from it. 
I'm not sure if this is the right place to ask technical questions about working with FALCON, but I couldn't find any other discussion place. 

I've been trying to work out how to set up a model to participate in the EvalAI challenge. For now, I'm just using a simple wiener filter while I make sure that my `*_decoder.py` and `*_sample.py` files work correctly. I've modeled my approach based on the sklearn decoder example you've provided. 
Locally, everything works fine, I've tested it on `m1` and `m2` with no problems. I've prepared a docker file (copied below) and made a submission with the EvalAI CLI using the `minival` phase. However, all of my submissions so fair failed on remote, even though the same code works locally. 

When I make a submission for `m2`, it seems to run fine, but the final status on EvalAI is "Failed". 
The `stderr` file associated with a run ([here](https://evalai.s3.amazonaws.com/media/submission_files/submission_478199/78793e1c-2920-4471-8205-3feb55247751.txt))  shows the scores printed out by the evaluator:
```
INFO:falcon_challenge.evaluator:Evaluation: Docker side
INFO:falcon_challenge.evaluator:Loading GT from /tmp/ground_truth.pkl
INFO:falcon_challenge.evaluator:Loading submission from /tmp/submission.pkl
INFO:falcon_challenge.evaluator:Phase: minival
20201019: 0.24531026060239944
20201020: 0.3941600642726192
20201027: 0.3963393503854379
20201028: 0.22413372183382727
Returning result from phase: minival: [{'minival_split_m2': {'Normalized Latency': 0.0034699689976421476, 'Held In R2 Mean': 0.31498584927357093, 'Held In R2 Std.': 0.08061598039606627, 'Held In 20201019 R2': 0.24531026060239944, 'Held In 20201020 R2': 0.3941600642726192, 'Held In 20201027 R2': 0.3963393503854379, 'Held In 20201028 R2': 0.22413372183382727}}]
```

This are exactly the same scores I get running it locally, so I would think that the evaluator ran correctly. There's nothing after that in either `stdout` or `stderr` files, but the status is still "Failed". 
Would you know what could be the cause of this, and how can I fix that?

COPY OF THE DOCKER FILE FOR REFERENCE
```
# Use a base Docker image with necessary dependencies
FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel

# Install additional system dependencies
RUN apt-get update && apt-get install -y git

# Clone the falcon-challenge repository
RUN git clone https://github.com/snel-repo/falcon-challenge.git
RUN pip install -e falcon-challenge

# Copy the requirements.txt file and install Python dependencies
COPY wiener_requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Set environment variables for local testing
ENV PREDICTION_PATH "/submission/submission.csv"
ENV PREDICTION_PATH_LOCAL "/tmp/submission.pkl"
ENV GT_PATH "/tmp/ground_truth.pkl"

# remote for EvalAI | local for local testing
ENV EVALUATION_LOC remote  

# when changing the split, also chage the CMD
ENV SPLIT "m1"
ENV BATCH_SIZE 4

# set to test for EvalAI | minival for local/remote development
ENV PHASE "minival"

ENV EVAL_DATA_PATH "/dataset/evaluation_data"

# Add necessary files to the Docker image
ADD ./wiener_bare wiener_bare
ADD ./utils utils
ADD ./models models
ADD ./wiener_decoder.py wiener_decoder.py
ADD ./wiener_sample.py wiener_sample.py
ADD ./hps.yaml hps.yaml

# # Set the working directory
# WORKDIR /app

# Specify the command to run the decoder
CMD ["python", "wiener_sample.py", "-s", "m1", "-m", "per-day"]

```

**Comment by cpandar** [comment]
I'm not the person to answer the technical questions here and definitely those folks will get back to you when we get a handle on it. Just wanted to mention how much we appreciate you taking the time to report back your issues/experiences!!! Also we appreciate your patience as we iron out these issues.

**Comment by FedeClaudi** [comment]
Of course, happy to help in a small way - FALCON is a greatly appreciated contribution to the field, and one that was really needed! I'm excited to see it being adopted as a benchmark in future work!

P.s. Joel and Brianna have been in touch by email and they have already addressed these issue, thank you!

**Comment by bmkarpowicz** [comment]
Issue has been resolved
